version: '3'

services:
  jackrabbit-rpc-server:
    build: .
    environment:
      RABBIT_URL: 'amqp://rabbit'
    entrypoint: ['node', 'examples/7-timeout-rpc/server']
    restart: on-failure
  jackrabbit-rpc-client:
    build: .
    environment:
      RABBIT_URL: 'amqp://rabbit'
    entrypoint: ['node', 'examples/7-timeout-rpc/client']
    restart: on-failure
  rabbit:
    image: rabbitmq:3.8.3-management-alpine@sha256:fe3889024ae255faa113c327e9ece13de63049ee8e9b5e3697c9d8918be697f2
    ports:
      - "5673:5672"
      - "15673:15672"
